In [19]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 


In [20]:
df = pd.read_csv('data.csv')
df.columns

Index(['rel_cont_area', 'rel_hull_area', 'num_defects', 'sum_angles', 'thumb',
       'index', 'middle', 'ring', 'pinky'],
      dtype='object')

In [21]:
# df.drop(columns=['rel_hull_area' , 'rel_cont_area'] , inplace = True)

In [22]:

from sklearn.model_selection import train_test_split

X = df[['rel_cont_area' , 'rel_hull_area' , 'num_defects','sum_angles']]
y = df[['thumb' , 'index' ,'middle' , 'ring' , 'pinky']]

X_train , X_test  , y_train , y_test  = train_test_split(X ,y , test_size=0.2 , stratify = y)
len(X_test)


2334

In [23]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train.to_numpy())
from sklearn.linear_model import LogisticRegression 
from sklearn.multiclass import OneVsRestClassifier , OneVsOneClassifier
lr = OneVsRestClassifier(LogisticRegression(penalty='l1' , solver = 'saga', max_iter=1000))
lr.fit(X_scaled , y_train)

OneVsRestClassifier(estimator=LogisticRegression(max_iter=1000, penalty='l1',
                                                 solver='saga'))

In [24]:

from sklearn.metrics import precision_score , recall_score , accuracy_score
y_predict = lr.predict(scaler.transform(X_test)) 
prec = precision_score(y_test ,y_predict , average ='macro' )
rec =  recall_score(y_test ,y_predict , average ='macro' )
acc= accuracy_score(y_predict , y_test)
print(prec , rec , acc)
 

0.8900406502113531 0.8614980641765673 0.705655526992288


d:\Python\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [25]:

from joblib import dump 
dump(lr ,'hand_gesture_model.pkl' )
 

['hand_gesture_model.pkl']

In [26]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score ,precision_score , recall_score
from sklearn.preprocessing import StandardScaler , MinMaxScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train.to_numpy())
knn = KNeighborsClassifier(n_neighbors = 4 , weights = 'distance' , n_jobs=-1)
knn.fit(X_scaled , y_train)

KNeighborsClassifier(n_jobs=-1, n_neighbors=4, weights='distance')

In [27]:

y_pred = knn.predict(scaler.transform(X_test))
prec = precision_score(y_test , y_pred , average = 'macro')
rec = recall_score(y_test , y_pred , average = 'macro')
acc = accuracy_score(y_test , y_pred )
print(prec , rec , acc)
 

0.981162665267739 0.978203933215436 0.9532990574121679


d:\Python\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [28]:
from sklearn.metrics import classification_report
from joblib import dump
dump(knn , 'knn_clf_hand_gesture.pkl')
dump(scaler , 'hand_gesture_scaler.pkl')

['hand_gesture_scaler.pkl']

In [29]:
print(classification_report(y_pred , y_test))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       460
           1       1.00      0.99      0.99      2091
           2       0.99      0.99      0.99      1721
           3       0.98      0.98      0.98      1330
           4       0.97      0.98      0.97       763

   micro avg       0.98      0.99      0.99      6365
   macro avg       0.98      0.98      0.98      6365
weighted avg       0.98      0.99      0.99      6365
 samples avg       0.98      0.99      0.98      6365



In [30]:
y_train.value_counts().to_numpy() / len(y_train)

array([0.24354441, 0.23390121, 0.17025608, 0.1535412 , 0.10521804,
       0.09353905])

In [31]:
np.unique(y_train.to_numpy() ,axis = 0 ,return_counts=True)

(array([[0, 1, 0, 0, 0],
        [0, 1, 1, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]], dtype=int64),
 array([1433, 1589, 2273, 2183,  982,  873], dtype=int64))

In [32]:

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly_feat = PolynomialFeatures(degree = 3)
X_feat = poly_feat.fit_transform(X_scaled)
thres = 0.6
lr2 = LinearRegression()
lr2.fit(X_feat , y_train)
y_pred = lr2.predict(poly_feat.transform(scaler.transform(X_test)))
y_pred =(y_pred > thres).astype(int)
prec = precision_score(y_test, y_pred , average = 'macro')
rec = recall_score(y_test , y_pred , average = 'macro')
acc = accuracy_score(y_test , y_pred )
print(prec , rec , acc)
 

0.9872594524170729 0.8961258753475608 0.8371893744644388


d:\Python\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [33]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=500,
    # min_samples_leaf = 1,
    max_features="log2",
    random_state=40,
    n_jobs=-1)
rfc.fit(X_scaled , y_train)

RandomForestClassifier(max_features='log2', n_estimators=500, n_jobs=-1,
                       random_state=40)

In [34]:
y_pred = rfc.predict(scaler.transform(X_test))
prec = precision_score(y_test, y_pred , average = 'macro')
rec = recall_score(y_test , y_pred , average = 'macro')
acc = accuracy_score(y_test , y_pred )
print(prec , rec , acc)

0.9853694092319847 0.9736043163666 0.9438731790916881


d:\Python\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [35]:

import joblib
joblib.dump(rfc , 'rand_forest_hand_gesture.pkl')


['rand_forest_hand_gesture.pkl']

In [36]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(criterion='entropy' , splitter = 'random')
dt_clf.fit(X_scaled , y_train)
y_pred = dt_clf.predict(scaler.transform(X_test))
prec = precision_score(y_test, y_pred , average = 'macro')
rec = recall_score(y_test , y_pred , average = 'macro')
acc = accuracy_score(y_test , y_pred )
print(prec , rec , acc)

0.9690102921224609 0.9666277454165388 0.9224507283633248


d:\Python\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
